include:
  - compose.infra.yaml
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      pgvector:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully

